[package]
name = "html5-picture"
version = "0.0.1-alpha"
authors = ["Lewin Probst <info@emirror.de>"]
edition = "2018"

[[bin]]
name = "html5-picture"

[dependencies]
clap = "3.0.0-beta.2"
log = "0.4.14"
walkdir = "2"
pretty_env_logger = "0.4.0"
